// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1wXBTgJK31udEhKASQ94yO7QOIREohKI',
    appId: '1:194903491762:web:27541dcc2c1177938fb5ab',
    messagingSenderId: '194903491762',
    projectId: 'imove-4804a',
    authDomain: 'imove-4804a.firebaseapp.com',
    storageBucket: 'imove-4804a.appspot.com',
    measurementId: 'G-V569ZBCGST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumkjNG6tvjjcnx68RUOsPqAhFsK9PApQ',
    appId: '1:194903491762:android:6d5444e9985a35428fb5ab',
    messagingSenderId: '194903491762',
    projectId: 'imove-4804a',
    storageBucket: 'imove-4804a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD89V9x2mrMW5C0HU1rHkfHIKuDvTgPv7k',
    appId: '1:194903491762:ios:caa44eacca27123b8fb5ab',
    messagingSenderId: '194903491762',
    projectId: 'imove-4804a',
    storageBucket: 'imove-4804a.appspot.com',
    iosBundleId: 'stockwalks.com.tracker',
  );
}
