openapi: 3.0.0
info:
  title: iMove Backend API
  description: This is the iMove Backend API
  version: 0.0.1
paths:
  /loginPage:
    post:
      summary: Login backend site
      description: According to different roles (Manager, Dispatcher, Packer, Driver), login backend site
      requestBody:
        description: User Request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':    
          description: Login successfully
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/LoginResponse'
        '400':    
          description: Server response error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBody'
              example:
                message: "Login Error"
  /order/{orderNumber}:
    get:
      summary: Get Orders by Order Number
      parameters:
        - in: path
          name: orderNumber
          schema:
            type: string
          required: true
          description: Get Orders by Order Number
      responses:
        '200':    
          description: An JSON of the order
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Order'
        '400':    
          description: Bad Request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBody'
              example:
                message: "Data not found"
components:
  schemas:
    ResponseBody:
      type: object
      properties:
        message:
          type: string
    UserRequest:
      type: object
      properties:
        role:
          type: string
        username:
          type: string
        password:
          type: string
      example:
        role: "packer"
        username: "packer1"
        password: "123456"
    LoginResponse:
      type: object
      properties:
        message:
          type: string
        user:
          $ref: '#/components/schemas/User'
        token:
          type: string
        role:
          type: string
      example:
        message: "login successfully"
        user:
            username: "packer1"
            password: "$2b$10$eNDcvieJhgvVuWp.aotLAerVPt0pgPflGc9AK17wMOEJkKjC3Ra5S"
            name: "Packer 1"
            address: ""
            email: ""
            gender: ""
            phone: ""
            photo: ""
        token: ""
        role: "packer"
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        name:
          type: string
        address:
          type: string
        email:
          type: string
        gender:
          type: string
        phone:
          type: string
        photo:
          type: string
      example:
        username: "packer1"
        password: "$2b$10$eNDcvieJhgvVuWp.aotLAerVPt0pgPflGc9AK17wMOEJkKjC3Ra5S"
        name: "Packer 1"
        address: ""
        email: ""
        gender: ""
        phone: ""
        photo: ""
    Order:
      type: object
      properties:
        createDate:
          type: string
          format: date-time
        shipmentStatus:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
              date:
                type: string
                format: date-time
        paymentStatus:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
              date:
                type: string
                format: date-time
        currencyCode:
          type: string
        remark:
          type: string
        totalAmount:
          type: number
        customer:
          type: string
        car:
          type: string
        driver:
          type: string
        parcelQty:
          type: number
        prefferedDeliveryDate:
          type: string
          format: date-time
        need_fridge:
          type: boolean
        sender:
          type: string
        consignmentID:
          type: string
        orderNumber:
          type: string
      example:
        createDate: "2023-04-01T10:30:00.000Z"
        shipmentStatus: 
          status: "prepared"
          date: "2023-04-01T00:00:00.000Z"
        paymentStatus:
          status: "unpaid"
          date: "2023-04-01T00:00:00.000Z"
        csurrencyCode: "AUD"
        remark": ""
        totalAmount: 420
        customer": "6435531588941c5e51959bc1"
        car: "643554d888941c5e51959bc3"
        driver: "643557b065b8ad5725de954b"
        parcelQty: 3
        prefferedDeliveryDate: "2023-04-01T00:00:00.000Z"
        need_fridge: true
        sender: "643fc42ac4fbf335914624c7"
        consignmentID: ""
        orderNumber: "SOF003101"